import React, { useState, useEffect } from "react";
import { useParams, Link, useNavigate } from "react-router-dom";
import { Compass, Calendar, DollarSign, Users, ChevronLeft, Download, Plus, Sparkles, Sliders, Share2, X, Mail } from "lucide-react";
import api from "../utils/api";
import toast from "react-hot-toast";
import Button from "../components/ui/Button";
import Skeleton from "../components/ui/Skeleton";
import ItineraryPlanner from "../components/trip/ItineraryPlanner";
import BudgetDashboard from "../components/trip/BudgetDashboard";
import AddActivityModal from "../components/trip/AddActivityModal";

const TripDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  
  const [trip, setTrip] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("itinerary");
  
  // Weather state
  const [weather, setWeather] = useState(null);
  const [weatherLoading, setWeatherLoading] = useState(true);

  // Sharing state
  const [isShareModalOpen, setIsShareModalOpen] = useState(false);
  const [shareEmail, setShareEmail] = useState("");
  const [isSharing, setIsSharing] = useState(false);

  // Modals & AI states
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [activeDayIdx, setActiveDayIdx] = useState(null);
  const [regeneratingDayIdx, setRegeneratingDayIdx] = useState(null);

  const fetchTrip = async () => {
    try {
      const response = await api.get(`/trips/${id}`);
      setTrip(response.data);
    } catch (err) {
      toast.error("Failed to load trip details");
      navigate("/dashboard");
    } finally {
      setLoading(false);
    }
  };

  const fetchWeather = async () => {
    try {
      const response = await api.get(`/trips/${id}/weather`);
      setWeather(response.data);
    } catch (err) {
      console.warn("Could not load weather details:", err);
    } finally {
      setWeatherLoading(false);
    }
  };

  useEffect(() => {
    fetchTrip();
    fetchWeather();
  }, [id]);

  const handleDragEnd = async (result) => {
    if (!result.destination) return;
    const { source, destination } = result;

    const sourceDayIdx = parseInt(source.droppableId, 10);
    const destDayIdx = parseInt(destination.droppableId, 10);

    const updatedDays = [...trip.days];
    const sourceActivities = [...updatedDays[sourceDayIdx].activities];
    const [movedActivity] = sourceActivities.splice(source.index, 1);

    if (sourceDayIdx === destDayIdx) {
      sourceActivities.splice(destination.index, 0, movedActivity);
      updatedDays[sourceDayIdx].activities = sourceActivities;
    } else {
      const destActivities = [...updatedDays[destDayIdx].activities];
      destActivities.splice(destination.index, 0, movedActivity);
      updatedDays[sourceDayIdx].activities = sourceActivities;
      updatedDays[destDayIdx].activities = destActivities;
    }

    // Optimistic Update
    setTrip({ ...trip, days: updatedDays });

    try {
      const res = await api.put(`/trips/${id}`, { days: updatedDays });
      setTrip(res.data);
    } catch (err) {
      toast.error("Failed to save reordered timeline");
      fetchTrip(); // Revert
    }
  };

  const handleDeleteActivity = async (dayIdx, actIdx) => {
    const updatedDays = [...trip.days];
    updatedDays[dayIdx].activities.splice(actIdx, 1);

    setTrip({ ...trip, days: updatedDays });

    try {
      const res = await api.put(`/trips/${id}`, { days: updatedDays });
      setTrip(res.data);
      toast.success("Event deleted");
    } catch (err) {
      toast.error("Failed to delete event");
      fetchTrip();
    }
  };

  const handleAddActivity = async (newActivity) => {
    const updatedDays = [...trip.days];
    updatedDays[activeDayIdx].activities.push(newActivity);

    setTrip({ ...trip, days: updatedDays });

    try {
      const res = await api.put(`/trips/${id}`, { days: updatedDays });
      setTrip(res.data);
      toast.success("Event added successfully!");
    } catch (err) {
      toast.error("Failed to add event");
      fetchTrip();
    }
  };

  const handleRegenerateDay = async (dayIdx) => {
    setRegeneratingDayIdx(dayIdx);
    try {
      const res = await api.post(`/trips/${id}/regenerate-day/${dayIdx}`);
      setTrip(res.data);
      toast.success(`Day ${dayIdx + 1} itinerary regenerated by AI!`);
    } catch (err) {
      toast.error(err.response?.data?.message || "Failed to regenerate day");
    } finally {
      setRegeneratingDayIdx(null);
    }
  };

  const triggerPDFExport = async () => {
    const toastId = toast.loading("Generating your styled PDF document...");
    try {
      const response = await api.get(`/trips/${id}/export-pdf`, {
        responseType: "blob",
      });
      
      const file = new Blob([response.data], { type: "application/pdf" });
      const fileURL = URL.createObjectURL(file);
      const link = document.createElement("a");
      link.href = fileURL;
      link.setAttribute("download", `${trip.destination.replace(/\s+/g, "_")}_itinerary.pdf`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(fileURL);
      toast.success("PDF Itinerary downloaded successfully!", { id: toastId });
    } catch (err) {
      toast.error("Failed to generate PDF. Please try again.", { id: toastId });
    }
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    toast.success("Shareable itinerary URL copied to clipboard!");
  };

  const handleShareEmail = async (e) => {
    e.preventDefault();
    if (!shareEmail.trim()) return toast.error("Please enter a recipient email");
    
    setIsSharing(true);
    try {
      await api.post(`/trips/${id}/share-email`, { email: shareEmail });
      toast.success(`Itinerary successfully emailed to ${shareEmail}!`);
      setShareEmail("");
      setIsShareModalOpen(false);
    } catch (err) {
      toast.error("Failed to share itinerary. Please try again.");
    } finally {
      setIsSharing(false);
    }
  };

  if (loading) {
    return (
      <div className="bg-brand-dark min-h-screen text-white p-8 max-w-6xl mx-auto flex flex-col gap-6">
        <Skeleton height="h-[60px]" />
        <Skeleton height="h-[200px]" />
      </div>
    );
  }

  return (
    <div className="bg-brand-dark min-h-screen text-white pb-20 print:bg-white print:text-black print:pb-0">
      {/* Detail Header / Print hidden */}
      <header className="bg-zinc-950/60 border-b border-zinc-900 px-6 py-4 flex items-center justify-between sticky top-0 z-30 print:hidden backdrop-blur-md">
        <button 
          onClick={() => navigate("/dashboard")}
          className="flex items-center gap-1 text-zinc-400 hover:text-white transition-colors text-xs font-semibold uppercase tracking-wider cursor-pointer"
        >
          <ChevronLeft size={16} />
          Dashboard
        </button>
        
        <div className="flex items-center gap-3">
          <Button variant="outline" className="px-4 py-2 text-xs flex items-center gap-1.5" onClick={() => setIsShareModalOpen(true)}>
            <Share2 size={14} />
            Share Trip
          </Button>
          <Button variant="outline" className="px-4 py-2 text-xs flex items-center gap-1.5" onClick={triggerPDFExport}>
            <Download size={14} />
            Export PDF
          </Button>
        </div>
      </header>

      {/* Main Container */}
      <main className="max-w-6xl w-full mx-auto px-6 mt-10 print:mt-0 print:px-0">
        {/* Info Grid Card */}
        <section className="glass rounded-xl p-8 border border-zinc-900 mb-8 print:border-none print:bg-transparent print:p-0 print:mb-12">
          <div className="flex flex-col md:flex-row justify-between items-start gap-4">
            <div>
              <span className="text-brand-accent text-xs font-bold uppercase tracking-widest flex items-center gap-1">
                <Compass size={12} />
                Bespoke Route
              </span>
              <h1 className="text-4xl font-semibold mt-1 print:text-3xl">{trip.destination}</h1>
            </div>
            
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 w-full md:w-auto mt-4 md:mt-0 bg-zinc-950/40 p-4 rounded-xl border border-zinc-900/60 print:grid-cols-4 print:border-none print:p-0 print:bg-transparent">
              <div>
                <span className="text-[10px] text-zinc-500 font-semibold uppercase tracking-wider block">Start Date</span>
                <span className="text-sm font-semibold font-sans mt-0.5 block">{trip.startDate}</span>
              </div>
              <div>
                <span className="text-[10px] text-zinc-500 font-semibold uppercase tracking-wider block">End Date</span>
                <span className="text-sm font-semibold font-sans mt-0.5 block">{trip.endDate}</span>
              </div>
              <div>
                <span className="text-[10px] text-zinc-500 font-semibold uppercase tracking-wider block">Travelers</span>
                <span className="text-sm font-semibold mt-0.5 block">{trip.travelers} Explorer{trip.travelers > 1 ? "s" : ""}</span>
              </div>
              <div>
                <span className="text-[10px] text-zinc-500 font-semibold uppercase tracking-wider block">Limit Budget</span>
                <span className="text-sm font-semibold font-sans mt-0.5 text-brand-accent block">${trip.budget}</span>
              </div>
            </div>
          </div>
        </section>

        {/* Interactive Map & Weather integration / Print hidden */}
        <section className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8 print:hidden">
          {/* Map Column */}
          <div className="md:col-span-2 glass rounded-xl overflow-hidden border border-zinc-900 h-[220px] relative">
            <iframe
              title="Destination Map"
              width="100%"
              height="100%"
              className="border-0 opacity-85 hover:opacity-100 transition-opacity duration-300"
              src={`https://maps.google.com/maps?q=${encodeURIComponent(trip.destination)}&t=&z=12&ie=UTF8&iwloc=&output=embed`}
              allowFullScreen
            ></iframe>
          </div>

          {/* Weather Widget */}
          <div className="glass rounded-xl p-6 border border-zinc-900 flex flex-col justify-between h-[220px]">
            {weatherLoading ? (
              <div className="flex flex-col gap-3 h-full justify-between">
                <Skeleton height="h-[20px]" />
                <Skeleton height="h-[60px]" />
                <Skeleton height="h-[20px]" />
              </div>
            ) : weather ? (
              <div className="flex flex-col h-full justify-between">
                <div className="flex justify-between items-start">
                  <div>
                    <span className="text-[10px] text-zinc-500 font-bold uppercase tracking-wider block">Local Weather</span>
                    <h4 className="text-lg font-bold truncate max-w-[140px]">{weather.city}</h4>
                  </div>
                  {weather.icon && (
                    <img
                      src={`https://openweathermap.org/img/wn/${weather.icon}@2x.png`}
                      alt={weather.description}
                      className="w-12 h-12 -mt-2 shrink-0 filter drop-shadow"
                    />
                  )}
                </div>

                <div className="flex items-baseline gap-1 my-2">
                  <span className="text-4xl font-extrabold font-sans tracking-tight">{weather.temp}°C</span>
                  <span className="text-zinc-500 text-xs font-light">Feels like {weather.feels_like}°C</span>
                </div>

                <div className="grid grid-cols-2 gap-2 text-zinc-400 text-[10px] uppercase font-bold pt-3 border-t border-zinc-900/60">
                  <div>Wind: <span className="text-white">{weather.wind} km/h</span></div>
                  <div>Humidity: <span className="text-white">{weather.humidity}%</span></div>
                  <div className="col-span-2 capitalize text-brand-accent tracking-wider font-semibold mt-0.5">{weather.description}</div>
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center h-full text-zinc-500 text-xs gap-1">
                <span>Weather data unavailable</span>
              </div>
            )}
          </div>
        </section>

        {/* Tab triggers / Print hidden */}
        <div className="flex border-b border-zinc-900 mb-8 gap-6 print:hidden">
          {["itinerary", "budget"].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`pb-3 text-sm font-semibold uppercase tracking-wider cursor-pointer border-b-2 transition-all ${
                activeTab === tab
                  ? "border-brand-accent text-white"
                  : "border-transparent text-zinc-500 hover:text-zinc-300"
              }`}
            >
              {tab === "itinerary" ? "Itinerary Editor" : "Budget Analytics"}
            </button>
          ))}
        </div>

        {/* Tab content */}
        <div className="print:block">
          {activeTab === "itinerary" && (
            <ItineraryPlanner
              days={trip.days}
              onDragEnd={handleDragEnd}
              onDeleteActivity={handleDeleteActivity}
              onOpenAddModal={(dayIdx) => {
                setActiveDayIdx(dayIdx);
                setIsAddModalOpen(true);
              }}
              onRegenerateDay={handleRegenerateDay}
              regeneratingDayIndex={regeneratingDayIdx}
            />
          )}

          {activeTab === "budget" && (
            <div className="print:hidden">
              <BudgetDashboard trip={trip} />
            </div>
          )}
        </div>
      </main>

      <AddActivityModal
        isOpen={isAddModalOpen}
        onClose={() => setIsAddModalOpen(false)}
        onAdd={handleAddActivity}
      />

      {/* Share Itinerary Modal */}
      {isShareModalOpen && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="glass max-w-md w-full rounded-xl border border-zinc-800/80 p-6 flex flex-col gap-4 relative animate-scaleIn">
            <button
              onClick={() => setIsShareModalOpen(false)}
              className="absolute top-4 right-4 text-zinc-500 hover:text-white p-1 rounded-lg hover:bg-zinc-900 cursor-pointer"
            >
              <X size={16} />
            </button>
            <div>
              <h3 className="text-xl font-bold">Share Itinerary</h3>
              <p className="text-zinc-500 text-xs mt-1">Copy the share link or send an email confirmation to a co-traveler.</p>
            </div>
            
            <div className="flex flex-col gap-3 mt-2">
              <button
                onClick={handleCopyLink}
                className="w-full py-3 border border-zinc-850 hover:border-zinc-800 bg-zinc-900/50 hover:bg-zinc-900 text-white rounded-lg flex items-center justify-center gap-2 text-xs font-semibold cursor-pointer transition-all"
              >
                <Share2 size={14} className="text-brand-accent" />
                Copy Link to Clipboard
              </button>
              
              <div className="flex items-center my-2">
                <div className="flex-grow border-t border-zinc-900"></div>
                <span className="flex-shrink mx-4 text-zinc-500 text-[10px] font-bold uppercase tracking-wider">Or email share</span>
                <div className="flex-grow border-t border-zinc-900"></div>
              </div>

              <form onSubmit={handleShareEmail} className="flex flex-col gap-3">
                <div className="flex flex-col gap-1.5">
                  <label htmlFor="shareEmail" className="text-zinc-500 text-[10px] font-bold uppercase tracking-wider px-1">Email Address</label>
                  <input
                    type="email"
                    id="shareEmail"
                    placeholder="e.g. friend@domain.com"
                    value={shareEmail}
                    onChange={(e) => setShareEmail(e.target.value)}
                    className="w-full bg-zinc-900/50 border border-zinc-800 rounded-lg px-4 py-3 text-xs text-white outline-none focus:border-brand-accent/50 transition-colors"
                  />
                </div>
                
                <Button
                  type="submit"
                  variant="accent"
                  className="w-full py-3 text-xs font-semibold flex items-center justify-center gap-1.5"
                  disabled={isSharing}
                >
                  <Mail size={14} />
                  {isSharing ? "Sending..." : "Send Email"}
                </Button>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default TripDetail;
