import React, { useState, useEffect } from "react";
import { useParams, Link, useNavigate } from "react-router-dom";
import { Compass, Calendar, DollarSign, Users, ChevronLeft, Download, Plus, Sparkles, Sliders } from "lucide-react";
import api from "../utils/api";
import toast from "react-hot-toast";
import Button from "../components/ui/Button";
import Skeleton from "../components/ui/Skeleton";
import ItineraryPlanner from "../components/trip/ItineraryPlanner";
import BudgetDashboard from "../components/trip/BudgetDashboard";
import AddActivityModal from "../components/trip/AddActivityModal";

const TripDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  
  const [trip, setTrip] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("itinerary");
  
  // Modals & AI states
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [activeDayIdx, setActiveDayIdx] = useState(null);
  const [regeneratingDayIdx, setRegeneratingDayIdx] = useState(null);

  const fetchTrip = async () => {
    try {
      const response = await api.get(`/trips/${id}`);
      setTrip(response.data);
    } catch (err) {
      toast.error("Failed to load trip details");
      navigate("/dashboard");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTrip();
  }, [id]);

  const handleDragEnd = async (result) => {
    if (!result.destination) return;
    const { source, destination } = result;

    const sourceDayIdx = parseInt(source.droppableId, 10);
    const destDayIdx = parseInt(destination.droppableId, 10);

    const updatedDays = [...trip.days];
    const sourceActivities = [...updatedDays[sourceDayIdx].activities];
    const [movedActivity] = sourceActivities.splice(source.index, 1);

    if (sourceDayIdx === destDayIdx) {
      sourceActivities.splice(destination.index, 0, movedActivity);
      updatedDays[sourceDayIdx].activities = sourceActivities;
    } else {
      const destActivities = [...updatedDays[destDayIdx].activities];
      destActivities.splice(destination.index, 0, movedActivity);
      updatedDays[sourceDayIdx].activities = sourceActivities;
      updatedDays[destDayIdx].activities = destActivities;
    }

    // Optimistic Update
    setTrip({ ...trip, days: updatedDays });

    try {
      const res = await api.put(`/trips/${id}`, { days: updatedDays });
      setTrip(res.data);
    } catch (err) {
      toast.error("Failed to save reordered timeline");
      fetchTrip(); // Revert
    }
  };

  const handleDeleteActivity = async (dayIdx, actIdx) => {
    const updatedDays = [...trip.days];
    updatedDays[dayIdx].activities.splice(actIdx, 1);

    setTrip({ ...trip, days: updatedDays });

    try {
      const res = await api.put(`/trips/${id}`, { days: updatedDays });
      setTrip(res.data);
      toast.success("Event deleted");
    } catch (err) {
      toast.error("Failed to delete event");
      fetchTrip();
    }
  };

  const handleAddActivity = async (newActivity) => {
    const updatedDays = [...trip.days];
    updatedDays[activeDayIdx].activities.push(newActivity);

    setTrip({ ...trip, days: updatedDays });

    try {
      const res = await api.put(`/trips/${id}`, { days: updatedDays });
      setTrip(res.data);
      toast.success("Event added successfully!");
    } catch (err) {
      toast.error("Failed to add event");
      fetchTrip();
    }
  };

  const handleRegenerateDay = async (dayIdx) => {
    setRegeneratingDayIdx(dayIdx);
    try {
      const res = await api.post(`/trips/${id}/regenerate-day/${dayIdx}`);
      setTrip(res.data);
      toast.success(`Day ${dayIdx + 1} itinerary regenerated by AI!`);
    } catch (err) {
      toast.error(err.response?.data?.message || "Failed to regenerate day");
    } finally {
      setRegeneratingDayIdx(null);
    }
  };

  const triggerPDFExport = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="bg-brand-dark min-h-screen text-white p-8 max-w-6xl mx-auto flex flex-col gap-6">
        <Skeleton height="h-[60px]" />
        <Skeleton height="h-[200px]" />
      </div>
    );
  }

  return (
    <div className="bg-brand-dark min-h-screen text-white pb-20 print:bg-white print:text-black print:pb-0">
      {/* Detail Header / Print hidden */}
      <header className="bg-zinc-950/60 border-b border-zinc-900 px-6 py-4 flex items-center justify-between sticky top-0 z-30 print:hidden backdrop-blur-md">
        <button 
          onClick={() => navigate("/dashboard")}
          className="flex items-center gap-1 text-zinc-400 hover:text-white transition-colors text-xs font-semibold uppercase tracking-wider cursor-pointer"
        >
          <ChevronLeft size={16} />
          Dashboard
        </button>
        
        <div className="flex items-center gap-3">
          <Button variant="outline" className="px-4 py-2 text-xs flex items-center gap-1.5" onClick={triggerPDFExport}>
            <Download size={14} />
            Export PDF
          </Button>
        </div>
      </header>

      {/* Main Container */}
      <main className="max-w-6xl w-full mx-auto px-6 mt-10 print:mt-0 print:px-0">
        {/* Info Grid Card */}
        <section className="glass rounded-xl p-8 border border-zinc-900 mb-8 print:border-none print:bg-transparent print:p-0 print:mb-12">
          <div className="flex flex-col md:flex-row justify-between items-start gap-4">
            <div>
              <span className="text-brand-accent text-xs font-bold uppercase tracking-widest flex items-center gap-1">
                <Compass size={12} />
                Bespoke Route
              </span>
              <h1 className="text-4xl font-semibold mt-1 print:text-3xl">{trip.destination}</h1>
            </div>
            
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 w-full md:w-auto mt-4 md:mt-0 bg-zinc-950/40 p-4 rounded-xl border border-zinc-900/60 print:grid-cols-4 print:border-none print:p-0 print:bg-transparent">
              <div>
                <span className="text-[10px] text-zinc-500 font-semibold uppercase tracking-wider block">Start Date</span>
                <span className="text-sm font-semibold font-sans mt-0.5 block">{trip.startDate}</span>
              </div>
              <div>
                <span className="text-[10px] text-zinc-500 font-semibold uppercase tracking-wider block">End Date</span>
                <span className="text-sm font-semibold font-sans mt-0.5 block">{trip.endDate}</span>
              </div>
              <div>
                <span className="text-[10px] text-zinc-500 font-semibold uppercase tracking-wider block">Travelers</span>
                <span className="text-sm font-semibold mt-0.5 block">{trip.travelers} Explorer{trip.travelers > 1 ? "s" : ""}</span>
              </div>
              <div>
                <span className="text-[10px] text-zinc-500 font-semibold uppercase tracking-wider block">Limit Budget</span>
                <span className="text-sm font-semibold font-sans mt-0.5 text-brand-accent block">${trip.budget}</span>
              </div>
            </div>
          </div>
        </section>

        {/* Tab triggers / Print hidden */}
        <div className="flex border-b border-zinc-900 mb-8 gap-6 print:hidden">
          {["itinerary", "budget"].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`pb-3 text-sm font-semibold uppercase tracking-wider cursor-pointer border-b-2 transition-all ${
                activeTab === tab
                  ? "border-brand-accent text-white"
                  : "border-transparent text-zinc-500 hover:text-zinc-300"
              }`}
            >
              {tab === "itinerary" ? "Itinerary Editor" : "Budget Analytics"}
            </button>
          ))}
        </div>

        {/* Tab content */}
        <div className="print:block">
          {activeTab === "itinerary" && (
            <ItineraryPlanner
              days={trip.days}
              onDragEnd={handleDragEnd}
              onDeleteActivity={handleDeleteActivity}
              onOpenAddModal={(dayIdx) => {
                setActiveDayIdx(dayIdx);
                setIsAddModalOpen(true);
              }}
              onRegenerateDay={handleRegenerateDay}
              regeneratingDayIndex={regeneratingDayIdx}
            />
          )}

          {activeTab === "budget" && (
            <div className="print:hidden">
              <BudgetDashboard trip={trip} />
            </div>
          )}
        </div>
      </main>

      <AddActivityModal
        isOpen={isAddModalOpen}
        onClose={() => setIsAddModalOpen(false)}
        onAdd={handleAddActivity}
      />
    </div>
  );
};

export default TripDetail;
